# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/archie/uwnotes/cprogrm711

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/archie/uwnotes/cprogrm711

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/archie/uwnotes/cprogrm711/CMakeFiles /home/archie/uwnotes/cprogrm711/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/archie/uwnotes/cprogrm711/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CPROGRM

# Build rule for target.
CPROGRM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CPROGRM
.PHONY : CPROGRM

# fast build rule for target.
CPROGRM/fast:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/build
.PHONY : CPROGRM/fast

assignment-8/Circle.o: assignment-8/Circle.cpp.o

.PHONY : assignment-8/Circle.o

# target to build an object file
assignment-8/Circle.cpp.o:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/Circle.cpp.o
.PHONY : assignment-8/Circle.cpp.o

assignment-8/Circle.i: assignment-8/Circle.cpp.i

.PHONY : assignment-8/Circle.i

# target to preprocess a source file
assignment-8/Circle.cpp.i:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/Circle.cpp.i
.PHONY : assignment-8/Circle.cpp.i

assignment-8/Circle.s: assignment-8/Circle.cpp.s

.PHONY : assignment-8/Circle.s

# target to generate assembly for a file
assignment-8/Circle.cpp.s:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/Circle.cpp.s
.PHONY : assignment-8/Circle.cpp.s

assignment-8/Point.o: assignment-8/Point.cpp.o

.PHONY : assignment-8/Point.o

# target to build an object file
assignment-8/Point.cpp.o:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/Point.cpp.o
.PHONY : assignment-8/Point.cpp.o

assignment-8/Point.i: assignment-8/Point.cpp.i

.PHONY : assignment-8/Point.i

# target to preprocess a source file
assignment-8/Point.cpp.i:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/Point.cpp.i
.PHONY : assignment-8/Point.cpp.i

assignment-8/Point.s: assignment-8/Point.cpp.s

.PHONY : assignment-8/Point.s

# target to generate assembly for a file
assignment-8/Point.cpp.s:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/Point.cpp.s
.PHONY : assignment-8/Point.cpp.s

assignment-8/Rectangle.o: assignment-8/Rectangle.cpp.o

.PHONY : assignment-8/Rectangle.o

# target to build an object file
assignment-8/Rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/Rectangle.cpp.o
.PHONY : assignment-8/Rectangle.cpp.o

assignment-8/Rectangle.i: assignment-8/Rectangle.cpp.i

.PHONY : assignment-8/Rectangle.i

# target to preprocess a source file
assignment-8/Rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/Rectangle.cpp.i
.PHONY : assignment-8/Rectangle.cpp.i

assignment-8/Rectangle.s: assignment-8/Rectangle.cpp.s

.PHONY : assignment-8/Rectangle.s

# target to generate assembly for a file
assignment-8/Rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/Rectangle.cpp.s
.PHONY : assignment-8/Rectangle.cpp.s

assignment-8/TestShape.o: assignment-8/TestShape.cpp.o

.PHONY : assignment-8/TestShape.o

# target to build an object file
assignment-8/TestShape.cpp.o:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/TestShape.cpp.o
.PHONY : assignment-8/TestShape.cpp.o

assignment-8/TestShape.i: assignment-8/TestShape.cpp.i

.PHONY : assignment-8/TestShape.i

# target to preprocess a source file
assignment-8/TestShape.cpp.i:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/TestShape.cpp.i
.PHONY : assignment-8/TestShape.cpp.i

assignment-8/TestShape.s: assignment-8/TestShape.cpp.s

.PHONY : assignment-8/TestShape.s

# target to generate assembly for a file
assignment-8/TestShape.cpp.s:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/TestShape.cpp.s
.PHONY : assignment-8/TestShape.cpp.s

assignment-8/Triangle.o: assignment-8/Triangle.cpp.o

.PHONY : assignment-8/Triangle.o

# target to build an object file
assignment-8/Triangle.cpp.o:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/Triangle.cpp.o
.PHONY : assignment-8/Triangle.cpp.o

assignment-8/Triangle.i: assignment-8/Triangle.cpp.i

.PHONY : assignment-8/Triangle.i

# target to preprocess a source file
assignment-8/Triangle.cpp.i:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/Triangle.cpp.i
.PHONY : assignment-8/Triangle.cpp.i

assignment-8/Triangle.s: assignment-8/Triangle.cpp.s

.PHONY : assignment-8/Triangle.s

# target to generate assembly for a file
assignment-8/Triangle.cpp.s:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/assignment-8/Triangle.cpp.s
.PHONY : assignment-8/Triangle.cpp.s

include/Main.o: include/Main.cpp.o

.PHONY : include/Main.o

# target to build an object file
include/Main.cpp.o:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/include/Main.cpp.o
.PHONY : include/Main.cpp.o

include/Main.i: include/Main.cpp.i

.PHONY : include/Main.i

# target to preprocess a source file
include/Main.cpp.i:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/include/Main.cpp.i
.PHONY : include/Main.cpp.i

include/Main.s: include/Main.cpp.s

.PHONY : include/Main.s

# target to generate assembly for a file
include/Main.cpp.s:
	$(MAKE) -f CMakeFiles/CPROGRM.dir/build.make CMakeFiles/CPROGRM.dir/include/Main.cpp.s
.PHONY : include/Main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... CPROGRM"
	@echo "... edit_cache"
	@echo "... assignment-8/Circle.o"
	@echo "... assignment-8/Circle.i"
	@echo "... assignment-8/Circle.s"
	@echo "... assignment-8/Point.o"
	@echo "... assignment-8/Point.i"
	@echo "... assignment-8/Point.s"
	@echo "... assignment-8/Rectangle.o"
	@echo "... assignment-8/Rectangle.i"
	@echo "... assignment-8/Rectangle.s"
	@echo "... assignment-8/TestShape.o"
	@echo "... assignment-8/TestShape.i"
	@echo "... assignment-8/TestShape.s"
	@echo "... assignment-8/Triangle.o"
	@echo "... assignment-8/Triangle.i"
	@echo "... assignment-8/Triangle.s"
	@echo "... include/Main.o"
	@echo "... include/Main.i"
	@echo "... include/Main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

